### ISSUE TITLE
Descriptor parsing functions call `error`

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/jvm-parser#4]
Functions `parseTypeDescriptor` and `parseMethodDescriptor` both call the haskell `error` function in the case of a parse error. This makes them not useful for parsing user-provided strings.

These functions should be changed to return `Maybe` types, so that a parse error can be indicated with `Nothing`.

**Comment by brianhuffman** [comment]
Now I see that those functions are not even exported; however, they would be useful if they *were* exported (along with the corresponding pretty-printing functions), but only if they had `Maybe` return types.

**Comment by hazelweakly** [comment]
Would it be beneficial for them to return a type like `Either` for richer error information?

**Comment by brianhuffman** [comment]
I don't know of any richer error information that would be useful in this case. These descriptor strings are usually not very long so the best error message would probably include the entire string you tried to parse.

**Comment by brianhuffman** [comment]
We should get rid of not just these calls to `error`, but all uses of `error` in the entire library. See GaloisInc/saw-script#924.

**Comment by brianhuffman** [comment]
The parser implementation additionally has lots of uses of refutable patterns like `let (ClassType cName, key) = ...`. These can result in pattern-match failures depending on user input, and so they should be completely avoided as well.
